### ISSUE TITLE
Define MaterialChoicePreference entries at runtime

### ISSUE THREAD

**Issue by mescalantea** [yarolegovich/MaterialPreferences#12]
First of all, thank you for this wonderful library. I am using MaterialChoicePreference to select the path where data is stored in my app, based on the available storage units. Currently I use a string array with the values "internal storage" and "micro sd" respectively. However, I need to assign these values at run time based on the availability of storage units at a given time. How could I achieve this?

**Comment by yarolegovich** [comment]
Yeah, that's possible. Check out [this API](https://github.com/yarolegovich/MaterialPreferences#storagemodule) and [an example implementation](https://github.com/yarolegovich/MaterialPreferences/blob/master/sample/src/main/java/com/yarolegovich/materialprefsample/FormInitializer.java).
